### ISSUE TITLE
Python scripts and states that use the Threshold filter are no longer compatible with PV 5.10

### ISSUE THREAD

**Issue by JonasLukasczyk** [topology-tool-kit/ttk-data#108]
The old Threshold python interface looked like this:
`someThresholdFilter.ThresholdRange = [5.0, 1000.0]`

this now has to be:
```
someThresholdFilter.LowerThreshold = 5.0
someThresholdFilter.UpperThreshold = 1000.0
```

one also may need to set the used threshold method:
```
someThresholdFilter.ThresholdMethod = "Between" # default
someThresholdFilter.ThresholdMethod = "Above Upper Threshold"
someThresholdFilter.ThresholdMethod = "Below Lower Threshold"
```

**Comment by lhofmann** [comment]
Here is how to do this in two lines while maintaining compatibility with ParaView < 5.10:
```python
try: thresholdFilter.ThresholdRange = [1, 2]
except: thresholdFilter.LowerThreshold = 1; thresholdFilter.UpperThreshold = 2; thresholdFilter.ThresholdMethod = 'Between'
```

**Comment by JonasLukasczyk** [comment]
@julien-tierny 
we are discussing how we should handle this. We either support only <5.10 or >=5.10. If we use Lutz's approach we handle both, but end users might be confused about this code snippet appearing all over the place. What is your opinion?

**Comment by lhofmann** [comment]
Another solution could be to provide two Python scripts where needed, and have two tabs "PV<5.10" and "PV&ge;5.10". (https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/)

**Comment by julien-tierny** [comment]
This has been fixed during last winter hackathon.
