### ISSUE TITLE
No ttkSurfaceGeometrySmoother examples

### ISSUE THREAD

**Issue by duncanspumpkin** [topology-tool-kit/ttk-data#157]
There are no examples of how to use ttkSurfaceGeometrySmoother but there are multiple references suggesting that an example exists:

1. https://topology-tool-kit.github.io/examples/persistentGenerators_fertility/
2. https://topology-tool-kit.github.io/examples/persistentGenerators_casting/
3. https://topology-tool-kit.github.io/examples/persistentGenerators_skull/

All of the above examples mention ttkSurfaceGeometrySmoother but don't use the class at all. I would suggest removing the cross references or even better adding an example.

**Comment by julien-tierny** [comment]
hi duncan,
sorry for the late reply :(
thanks for your message.

these examples do use ttkSurfaceGeometrySmoother indeed, but only the paraview state file.
to see how to use them in python, load the paraview state file and export it to python (file, save state, select the *py extension). I hope this helps!
