### ISSUE TITLE
Nested Tracking Graph example does not work

### ISSUE THREAD

**Issue by neonguyen1287** [topology-tool-kit/ttk-data#17]
I'm able to run all examples except the nested tracking graph. Got a bunch of error messages "No proxy that matches: group=filters and proxy=MeshGraph were found... Could not create a proxy of group: filters type:MeshGraph"
![ttk_ntg_error](https://user-images.githubusercontent.com/51726086/59313959-ee5b6d00-8c67-11e9-8e76-0c69cc1126e0.jpg)

**Comment by julien-tierny** [comment]
hi, 

thanks for posting this issue.

> I'm able to run all examples except the nested tracking graph. 
it seems that you are running ttk-0.9.7. 
however, the nested tracking graphs were not available yet in that version.

please install the current master branch (https://github.com/topology-tool-kit/ttk.git) to access support for nested tracking graphs.

thanks for letting us know if you run into any other issue.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by duongnb09** [comment]
Hi Julien,

I've updated to the latest version of ttk which is TTK 0.9.8 with Paraview 5.6.0 64bit on Windows 10. The other example was running fine. For the nested tracking graph (NTG), the paraview window just pop up and disappeared very quickly without any messages.  Does NTG require optional dependencies?

Thanks for the help!

**Comment by neonguyen1287** [comment]
Hi Julien,

I've updated to the latest version of ttk which is TTK 0.9.8 with Paraview 5.6.0 64bit on Windows 10. The other example was running fine. For the nested tracking graph (NTG), the paraview window just pop up and disappeared very quickly without any messages. Does NTG require optional dependencies?

Thanks for the help!

**Comment by julien-tierny** [comment]
hi,

> Does NTG require optional dependencies?
yes: graphviz. ttk should run with an error message if it's not installed.

can you launch this example from git bash (assuming you installed git) and report the messages that you see on the git bash console?
based on that, @JonasLukasczyk will be able to help.

thanks.
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
hi there,
I close the issue for now.
please feel free to re-open if you get some news on your end.
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
