### ISSUE TITLE
ttk-data PR #21 is broken with ttk:dev (PR #304)

### ISSUE THREAD

**Issue by julien-tierny** [topology-tool-kit/ttk-data#22]
@JonasLukasczyk 
@pierre-guillou
the following state files look broken:
- states/cinemaReader.pvsm
- states/nestedTrackingGraph.pvsm
- states/trackingFromOverlap.pvsm

thanks for having a quick look!
cheers

**Comment by pierre-guillou** [comment]
Those three states use the CinemaQuery filter.
I think that the last modifications I made to Jonas' branch (specifically the one about CinemaQuery input ports) may be causing those issues.
Pierre

**Comment by JonasLukasczyk** [comment]
Yes, no worries. I'm on it and will open a new ttk-data PR.

**Comment by julien-tierny** [comment]
hi there,
it looks like PR #24 fixed most of it but states/trackingFromOverlap.pvsm still looks weird (plus I suspect states/nestedTrackingGraph.pvsm got much slower).

@JonasLukasczyk 
can you have a quick look at this?
cheers

**Comment by julien-tierny** [comment]
hi there, 
commit 8665a9d should have fixed the issue. should be ok now. thanks all!
